// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqVxXxORGFxvcL3t3dxMKuqxRWeLEMDAs',
    appId: '1:401850850820:web:6b05eca6ab9fabff30df51',
    messagingSenderId: '401850850820',
    projectId: 'bistar-me-chai',
    authDomain: 'bistar-me-chai.firebaseapp.com',
    storageBucket: 'bistar-me-chai.appspot.com',
    measurementId: 'G-FHNETGPDL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNSPN4h0yBIJz0-UiE8MIVnJCTbukjk1Y',
    appId: '1:401850850820:android:279afcc1a1bff32e30df51',
    messagingSenderId: '401850850820',
    projectId: 'bistar-me-chai',
    storageBucket: 'bistar-me-chai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfEu-L32EGxUEkbwzbjuPntf72MPvqnME',
    appId: '1:401850850820:ios:435305af5ea1c4a630df51',
    messagingSenderId: '401850850820',
    projectId: 'bistar-me-chai',
    storageBucket: 'bistar-me-chai.appspot.com',
    iosBundleId: 'com.example.chai',
  );
}
